name: CI - Build & Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: buyhood
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for MySQL to be ready
        run: |
          echo "MySQL 컨테이너가 완전히 기동될 때까지 기다림(mysql 준비될 시간 확보)"
          sleep 40
          
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew clean test -Dspring.profiles.active=ci
