name: Deploy to EC2

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Plqafgh12!
          MYSQL_DATABASE: buyhood
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Save SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/deploy_key.pem
        chmod 600 ~/.ssh/deploy_key.pem

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Copy JAR file to EC2
      run: |
        scp -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no \
        build/libs/*.jar \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app.jar

    - name: Deploy on EC2 via SSH
      run: |
        ssh -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "EC2 접속 성공"
          pkill -f 'java -jar' || true
          nohup java -jar /home/${{ secrets.EC2_USER }}/app.jar > app.log 2>&1 &
          echo "JAR 실행 완료. 로그 보기:"
          tail -n 10 app.log || echo "아직 로그 없음"
        EOF
